services:
  postgresql:
    container_name: ecommerce_pg_sql
    image: postgres
    environment:
      POSTGRES_USER: foreverNMG
      POSTGRES_PASSWORD: foreverNMG
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - ecommerce-microservices-net
    restart: unless-stopped

  pgadmin:
    container_name: ecommerce_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - ecommerce-microservices-net
    restart: unless-stopped

  zipkin:
    container_name: ecommerce_zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - ecommerce-microservices-net

  mongodb:
    image: mongo
    container_name: ecommerce_mongo_db
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=foreverNMG
      - MONGO_INITDB_ROOT_PASSWORD=foreverNMG

  mongo-express:
    image: mongo-express
    container_name: ecommerce_mongo_express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=foreverNMG
      - ME_CONFIG_MONGODB_ADMINPASSWORD=foreverNMG
      - ME_CONFIG_MONGODB_SERVER=mongodb

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: ecommerce_zookeeper
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    networks:
      - ecommerce-microservices-net
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: ecommerce_kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    networks:
      - ecommerce-microservices-net

  mail-dev:
    container_name: ecommerce-mail-dev
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - ecommerce-microservices-net
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.13.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - ecommerce-microservices-net
  logstash:
    container_name: logstash
    hostname: logstash
    image: docker.elastic.co/logstash/logstash:8.13.0
    volumes:
      #- ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro,Z
      - ./logstash.conf:/usr/share/logstash/config/logstash.conf
    ports:
      - "9600:9600"
      - "7777:7777"
    networks:
      - ecommerce-microservices-net
    depends_on:
      - elasticsearch
    restart: unless-stopped

networks:
  ecommerce-microservices-net:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  mongo:
  elasticsearch: