eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
name:
  value: foreverNMG
spring:
  application:
    name: config-server
  cloud:
    config:
      override-system-properties: false

management:
  tracing:
    sampling:
      probability: 1.0